### ISSUE TITLE
New approch for stats

### ISSUE THREAD

**Issue by guillaumev** [humanitarianresponse/site#10]
Find a better way to store and provide statistics to field offices

**Comment by guillaumev** [comment]
Initial thoughts: define 2 custom variables of type page (see http://piwik.org/docs/custom-variables/ ):

* one "space" variable which will provide the space id of the page being viewed
* one "bundle" variable which will provide the bundle id of the page being viewed

**Comment by guillaumev** [comment]
Data should now be sent to the Piwik server and stored, so it will make it easier to retrieve them. However, the data visualization still needs to be created... I'm thinking about creating a Piwik widget, but there might be easier options...

**Comment by guillaumev** [comment]
This is how the new stats widget will show up:

![hr_stats_piwik](https://cloud.githubusercontent.com/assets/90224/8985403/8181eb3a-36d7-11e5-991a-f4cbed1844c2.png)

**Comment by emmajane** [comment]
Re-closing the issue. Was accidentally re-opened with my label-making.
