### ISSUE TITLE
When filtering an API request, the pager doesn't keep the filters

### ISSUE THREAD

**Issue by pcambra** [humanitarianresponse/site#100]
See example on https://www.humanitarianresponse.info/api/v1.0/documents?filter[document_type]=50353
The documents displaying are the total amount of documents and shouldn't be paged.

The first thing to try is to upgrade Restful module to the right version and see if the issue still happens.

**Comment by javedyousafzai** [comment]
can we close it?

**Comment by pcambra** [comment]
Count is good and pager doesn't show up.
