### ISSUE TITLE
Organizations in HR.info not appearing in HID - need to check the API

### ISSUE THREAD

**Issue by javedyousafzai** [humanitarianresponse/site#105]
I got the request via 'Form filled' to add British Red Cross in HR.info and this comes from the form when people try to add themselves to HID. I was pretty sure that we have this organzaton in HR.info and its there. See the [example API] (https://www.humanitarianresponse.info/api/v1.0/organizations/17190) but when I go to HID and try to edit (not doing it but to see the drop-down) I don't see the British Red cross - see the screen-shot

![image](https://cloud.githubusercontent.com/assets/3966785/10013302/991b7e42-6110-11e5-9a03-8a76ad60fc22.png)

I actually had an issue with our HR.info API where I could not find the actual number of document types, for which I asked Pedro and he added an issue https://github.com/humanitarianresponse/site/issues/100.

Can you please check yourself as @pcambra is away for a week and I am afraid if those Restful API module is not working properly, it will affect the control vocabulary drop-down lists.

**Comment by guillaumev** [comment]
Should be fixed in the next hrinfo deploy...

**Comment by javedyousafzai** [comment]
OK great.

**Comment by javedyousafzai** [comment]
can we close this?

**Comment by guillaumev** [comment]
Yes, closing.
