### ISSUE TITLE
Indicator Registry Translation - How to keep track of the changes in 'English' version?

### ISSUE THREAD

**Issue by javedyousafzai** [humanitarianresponse/site#107]
@/all there is a volunteer group (Translators Without Borders) who are going to translate the indicators in our Indicator Registry. One question that has come up is - how can we know if an (English) indicator is changed in the future and thus needs to be translated again into other languages.
Does the internationalization module (or whatever we are using) handle this ability?

@pcambra can the current module tell us or notify us if the changes are made in the Indicator registry )(content)??

**Comment by humphreymburu** [comment]
Just done some digging when editing lets say an content type operations for example CAR , there is an option ' Flag translations as outdated ' check box to mark translations as outdated and in need of revision.I think it's possible !

**Comment by emmajane** [comment]
Is this initiative ongoing, or should we close this issue?

**Comment by emmajane** [comment]
No news in a month. Closing this issue.
