### ISSUE TITLE
Cluster title (Mandatory field) is missing in Operational website  

### ISSUE THREAD

**Issue by javedyousafzai** [humanitarianresponse/site#108]
See the Nepal website. If you browse as anonymous and then click on the Education cluster, the main title which is mandatory is missing from the tab and when I edit it, there is no title provided.

I am not sure how this happens as this is mandatory field and the website should not allow this to happen, which is very weird. -See the screenshot.

I am going to add the title now but we need to investigate this issue as this is not the fist time I am seeing this. 
@pcambra I am tagging @guillaumev as well as I showed this to him when he was here couple weeks ago. I think It was for Pakistan website,.

![image](https://cloud.githubusercontent.com/assets/3966785/10069795/c885ce9a-62ae-11e5-96af-1f3a7cd6ade2.png)

# Tasks

- Review all clusters -- https://www.humanitarianresponse.info/en/admin/content (filter by cluster) -- to see if there are any with a blank name.
- If there is a blank title, add a title
- As a comment on the issue, identify which nodes had blank titles.

**Comment by pcambra** [comment]
We can check if we have more clusters without title and see if we can fix those

**Comment by javedyousafzai** [comment]
Pakistan office was facing similar issue today for the 'Food Security' cluster today and I added title there.

**Comment by humphreymburu** [comment]
Hi @team "https://www.humanitarianresponse.info/en/operations/yemen" was the only page that lacked title ,which I have updated.

**Comment by emmajane** [comment]
Titles have been updated. This may have been issues with an earlier migration, but should no longer be an issue.
