### ISSUE TITLE
Improving RSS feeds feature in HR.info

### ISSUE THREAD

**Issue by javedyousafzai** [humanitarianresponse/site#110]
we will need to improve the way we show the RSS feeds in HR.info i.e. make them more operation and content specific. If I go to to Iraq website, I should be able to get all the content for Iraq website and If I browse the Documents and apply filters there then I should get the RSS feed for those results as well. 

For example; I want to get the RSS feed for all the documents with Document Type='Assessment Report' see the [documents] (https://www.humanitarianresponse.info/en/operations/iraq/documents/document-type/assessment-report).

Here we should provide an icon for 'RSS feeds' so viewers can get the feeds. We had this feature in HR,info 1.9 but we have not added it in HRinfo 2.0

@pcambra I am assigning this to you but you can ask @MartinMaritim or @humphreymburu to look into it.

![image](https://cloud.githubusercontent.com/assets/3966785/10101158/197277d4-6397-11e5-92ae-90d55e8156a6.png)

**Comment by javedyousafzai** [comment]
this case is related to [issue] (https://github.com/humanitarianresponse/site/issues/99), so if we fix this one, it should help Mark as well - getting all the documents he needs to check for wrong tagging.

**Comment by pcambra** [comment]
I understand, but I wouldn't change the menu link you're highlighting, that belongs to a set of generic links that I would honestly expect to be fixed (a general rss feed, if you will)

We can add a RSS icon in specific listings, for example, search results, but I'd need to know which ones are affected.

**Comment by pcambra** [comment]
Check out how RW is doing it: http://reliefweb.int/updates?primary_country=13&format=3&vulnerable_groups=6870#content

**Comment by javedyousafzai** [comment]
The highlighted was just an example, but yes we will need to add the 'RSS' feeds to the 'Documents, Maps, Assessments and Blogs and also the search results when people apply fitlers. Just like Reliefweb does.

For example, when someone browse the [Documents](https://www.humanitarianresponse.info/en/operations/nepal/documents) or [Maps] (https://www.humanitarianresponse.info/en/operations/nepal/infographics) on Nepal website, they can also get those results in RSS feeds.

**Comment by pcambra** [comment]
I think we have some glitches on some cluster filters:
https://www.humanitarianresponse.info/en/operations/nepal/documents/feed/themes/age
shows slightly different results than
https://www.humanitarianresponse.info/en/operations/nepal/documents/themes/age


Let's keep this one open until we fix those

**Comment by emmajane** [comment]
Sample URLs now show the same result. Thanks, Pedro!
