### ISSUE TITLE
Improved Speed for logged-in users (MENA-IMPACT feedback - 8 votes)

### ISSUE THREAD

**Issue by javedyousafzai** [humanitarianresponse/site#114]
I wasn't sure if we have cases for this issue already. This is related to the speed improvements for users who log in and add content to the site, make changes to the pages using panelizers, etc. 

@pcambra we agreed to have the list of users who contributed contribute content on regular basis and capture their 'user journey'. I guess #102 is related to this one right?

Also I wanted to share with you my findings from a skype call with Nigeria office. They have been trying  various times to upload a documents but every time they click on the 'upload' button, the cursor runs for 20, 35 or sometime 30 minutes and the document doesn't load - see the screenshot. 
![image](https://cloud.githubusercontent.com/assets/3966785/10164332/41a4a1da-66b9-11e5-991a-b106dc35ae58.png)

I asked them to do the speedtest and they shared with the result in the following screenshot. Although they don't have high bandwidth but this is the fact in some field offices. These are the facts we need to consider when we investigate for performance improvement. 
![image](https://cloud.githubusercontent.com/assets/3966785/10164429/b7a9b654-66b9-11e5-9219-abd021f3aba2.png)

**Comment by pcambra** [comment]
Do you have information about the file sizes they're trying to upload?

**Comment by pcambra** [comment]
![hrinfo-error-upload](https://cloud.githubusercontent.com/assets/104912/11468672/47ceaedc-9749-11e5-9603-85839330d5e3.png)

**Comment by Yaelle01** [comment]
@pcambra, I believe that the file size of James doc was 1.5 MB . @MartinMaritim and @humphreymburu , please check in the info@hr.info inbox for the case of Nigeria and addition info from that email exchange into the case. Please contact James and do the same Javed did with Nigeria, so that we have a better idea of what could be the problem. @pcambra , agree?

**Comment by pcambra** [comment]
We would also need to clarify in what content types this is happening, is only documents or sitewide?
I'm working in having better UX for uploads so at least they can see a progressbar.

@Yaelle01 you mentioned that the problem wasn't really the upload of the files as much as the saving of the form, in that case we might be experiencing the same issue that we've reported in #96

**Comment by humphreymburu** [comment]
Hi @team I have tested upload of documents and I have not experienced any issue upload seems fine .I have also sent an email to James requesting him to speed test just as Javed did with nigeria.

**Comment by pcambra** [comment]
We might want to consider https://www.drupal.org/project/plupload

**Comment by pcambra** [comment]
Let's move to a progressbar widget instead for the moment to indicate the real progress. Not likely to solve the issue, but it will give the user a better experience and more information of what's happening (and us too)

**Comment by humphreymburu** [comment]
Hi @Team James managed to reply my request  regarding upload and download speeds using speedtest.net , Find link below .

http://www.speedtest.net/results.php?ct=u&sh=28bf6ebbe369c25b298c2cbde01fe52b&ria=0&s=0

I still think we need more info to diagnose the real culprit!

**Comment by emmajane** [comment]
This was intermittent issues with S2, which were revealed in more detail after we changed to a progressbar. Closing.
