### ISSUE TITLE
remove the 'Check-in' tab from HR.info spaces

### ISSUE THREAD

**Issue by javedyousafzai** [humanitarianresponse/site#115]
Hi @pcambra ! see the screenshot here. We need to remove this button from the spaces in HR.info and it actually confuses people when the check-into HID to specific operations.

Way back then, we provided this functionality to let users (registered in HR.info) check-in to the site so they could be part of the contacts list in HR.info, but now we are going to switch to HID contacts and some people have already got confused with this option in HR.info.

Can you hide/remove this button as 'hot fix' and release in our production server today?

![image](https://cloud.githubusercontent.com/assets/3966785/10190349/2fc1fc48-676c-11e5-970f-609a540e4a80.png)

**Comment by pcambra** [comment]
Just to clarify, the check-in feature is not needed anymore and we need to remove it from the site.

There's also a listing of "My Check ins", do we need to remove that as well?
https://www.humanitarianresponse.info/en/check-ins

There's a HID checkins part that I guess we're keeping, do we remove the HRinfo local one?

**Comment by javedyousafzai** [comment]
OK lets rename ti to 'My Spaces' please.

**Comment by javedyousafzai** [comment]
@pcambra I am closing this case. thx

**Comment by emmajane** [comment]
"Check-in" tab is no longer visible; closing the issue.

![2015-12-03 at 09 25](https://cloud.githubusercontent.com/assets/1299320/11556632/e71a5e98-999f-11e5-91c3-943eed30b5f9.png)

**Comment by pcambra** [comment]
We still need to actually remove the contacts feature when all the spaces move to HID (related to #195)

**Comment by emmajane** [comment]
I've created follow-up tasks for #195 (and a label / milestone) at: #217, #216, #215.
