### ISSUE TITLE
Simulation repeating on the Cluster operation Map

### ISSUE THREAD

**Issue by javedyousafzai** [humanitarianresponse/site#122]
https://www.humanitarianresponse.info/en/coordination/clusters/countries

![image](https://cloud.githubusercontent.com/assets/3966785/10276843/77766ab2-6b52-11e5-8a3c-67040aeee29a.png)

Can we fix it please?

**Comment by javedyousafzai** [comment]
I don't see the repeating names under 'Malawi' anymore. @MartinMaritim, @humphreymburu ! did one of you fix it or its fixed by itself?

**Comment by humphreymburu** [comment]
@javedyousafzai I fixed it ...

**Comment by javedyousafzai** [comment]
thanks @humphreymburu

**Comment by javedyousafzai** [comment]
OK I will close this case then.
