### ISSUE TITLE
Picking up organization acronyms in HID does not always work

### ISSUE THREAD

**Issue by guillaumev** [humanitarianresponse/site#130]
Card:
A user should find his/her organization by acronym, when editing their profile.

Conversation:

Javed Khan noticed that some (not all!) organization acronyms are not picked up in Humanitarian ID, when editing a profile. This applies for example for UNHCR, ACTED, GIZ, UNFPA. All those organizations exist with acronyms in HR.info as well but we cannot figure out why some organizations (like OCHA or UNICEF) are picked up by the system and others are not.

Completion:
All organizations that exist with an acronym, should be found in the widget by their acronym

See for example https://www.humanitarianresponse.info/hid/organizations/extended/autocomplete/UNHC which returns a 500 Internal server error...

**Comment by javedyousafzai** [comment]
can we close this case?
