### ISSUE TITLE
Submit to Reliefweb - need to check the feature

### ISSUE THREAD

**Issue by javedyousafzai** [humanitarianresponse/site#133]
Can someone please check this feature? Mali office has reported that it is not working.

**Comment by MartinMaritim** [comment]
@javedyousafzai I have tested this by using my email and it seems to work. Wondering if the Mali office got any error/warning message when posting the document with the 'submit to reliefweb' flag?

**Comment by javedyousafzai** [comment]
OK @MartinMaritim , can you please get in touch with Sekou Traoere or Mohamed Dabo (dabom@un.org) and ask them?

thanks

**Comment by MartinMaritim** [comment]
Thanks @javedyousafzai. I will.

**Comment by javedyousafzai** [comment]
@MartinMaritim, please see the comments from Shucih.

lets try to make a title of the document and other meta-data we can provide so its more human readable.

**Comment by javedyousafzai** [comment]
can we close this case @MartinMaritim ??

**Comment by javedyousafzai** [comment]
@MartinMaritim if this issue is resolved, please close it.

**Comment by MartinMaritim** [comment]
I believe it is resolved. Closing ...
