### ISSUE TITLE
Switch HR.info / Humanitarian ID on 16 October

### ISSUE THREAD

**Issue by Yaelle01** [humanitarianresponse/site#140]
Hi @javedyousafzai and @pcambra , 

Here's the list of countries using HR.info contacts with an additional column on whether they should be switched to HID on 16 Oct or not (done / switch / wait): 

https://docs.google.com/spreadsheets/d/13ALB9MXxdJ0y_Gc3b9zezrZr5ADAqDQchK_2A_hR1b4/edit?usp=sharing

At the moment, 11 countries are ready to switch, though I assume this could increase within the next 24 hours. I will keep updating the above list.

**Comment by javedyousafzai** [comment]
Here are the steps I would suggest;
1. Before HR.info team switch contacts for operation e.g. Iraq, Yaelle sends a short message to IM Unit (including website focal point) and mention the date
2. HR.info team take backup of those contacts – just in case
3. HR.info team switch the contacts

**Comment by pcambra** [comment]
For number 2, it's not needed as we don't delete the contacts, we just switch the contacts menu url.
Once every single operation is moved to hid we can think a solution of archiving and deleting the hrinfo contacts.

**Comment by javedyousafzai** [comment]
For step #2' yes agreed

**Comment by humphreymburu** [comment]
@pcambra I finished the 30 operations as requested by @Yaelle01.
