### ISSUE TITLE
Disable 'Add contact' feature in HR.info

### ISSUE THREAD

**Issue by javedyousafzai** [humanitarianresponse/site#145]
In order to stop adding contact in HR.info, we are going to disable the 'Add Contact' feature for now in all the spaces/opertions so that site focal points can add contacts directly in HID using 'Add responders'. For that @pcambra will add a page with graphic with a text" **We are no longer using Humanitarian Response.info platform for managing contacts. Please visit Humanitarian ID and use "[Create a Responder] (https://app.humanitarian.id/#/createaccount)" to add new contact.

For the message background we should use the one similar to what we used for [Morocco closed contacts](https://www.humanitarianresponse.info/en/node/70701/hid_contacts).

**Regarding the dates**; 
If we provide the design and text to @pcambra by Wednesday **21st October**, he can add it to the next Monday release.

We will keep these settings i.e. 'Disabled contacts' until **November 15th** so we make sure there is no complaint or any legitimate request to use HR.info 'Add contacts' feature any more.

Starting Mid **November 16th**, we will do the following; 
1. archive all the existing contacts in HR.info 
2. @pcambra start working on removing the 'Add contact' feature permanently
3. and finally remove the 'Contact' feature from HR.info which means every operation/HQ space by then will be using HID

@andrejverity, @pcambra and @Yaelle01 please add comments if you have any regarding this case or want to make changes to the above dates.

**Comment by andrejverity** [comment]
Suggest changing the text a bit (as we want to also suggest people may want to Check-in someone vs just Creating a Responder).  How about this:

>Contacts in HumanitarianResponse.info are now powered by Humanitarian ID (HID). In order to add  a new contact, you will need to go to HID (http://humanitarian.id) and either Check-in the responder or use the "Create A Responder" function.

Below is a screen capture for **Ignacio** to use for the background blur (like we did on the private contacts page - example: https://www.humanitarianresponse.info/en/node/70701/hid_contacts)

Ignacio: can you do a quick mock-up and let Javed know?

![hr info_add_contact](https://cloud.githubusercontent.com/assets/13421097/10579070/57b9f8fe-7676-11e5-98f3-be49e17556d3.PNG)

**Comment by javedyousafzai** [comment]
@pcambra , please see the mockup done by Ignacio. https://drive.google.com/folderview?id=0B4DjXe64lR7sWHlFZkxzYzh0REU&usp=drive_web

For the text in the box, please use the following;
**Contacts in HumanitarianResponse.info are now powered by Humanitarian ID (HID). In order to add a new contact, you will need to go to HID (http://humanitarian.id) and either Check-in the responder or use the "Create A Responder" function**

**Comment by pcambra** [comment]
Here are a few screenshots of the PR above

![screen shot 2015-10-21 at 16 57 32](https://cloud.githubusercontent.com/assets/104912/10642305/f64c6c1e-7814-11e5-915a-f8be82c15ca1.png)
![screen shot 2015-10-21 at 16 57 23](https://cloud.githubusercontent.com/assets/104912/10642306/f650dce0-7814-11e5-9e9d-d369d0e736ba.png)
![screen shot 2015-10-21 at 16 57 14](https://cloud.githubusercontent.com/assets/104912/10642304/f64a6540-7814-11e5-8fd6-de0c2925d99e.png)

**Comment by andrejverity** [comment]
Looking good!

On Wednesday, 21 October 2015, Pedro <notifications@github.com> wrote:

> Here are a few screenshots of the PR above
>
> [image: screen shot 2015-10-21 at 16 57 32]
> <https://cloud.githubusercontent.com/assets/104912/10642305/f64c6c1e-7814-11e5-915a-f8be82c15ca1.png>
> [image: screen shot 2015-10-21 at 16 57 23]
> <https://cloud.githubusercontent.com/assets/104912/10642306/f650dce0-7814-11e5-9e9d-d369d0e736ba.png>
> [image: screen shot 2015-10-21 at 16 57 14]
> <https://cloud.githubusercontent.com/assets/104912/10642304/f64a6540-7814-11e5-8fd6-de0c2925d99e.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/humanitarianresponse/site/issues/145#issuecomment-149942454>
> .
>


-- 
Andrej
--------------
blog.veritythink.com

**Comment by javedyousafzai** [comment]
nice!

**Comment by pcambra** [comment]
@andrejverity @Yaelle01 we haven't started to remove the "Contacts" feature permanently, is this something that we still have on track?

**Comment by Yaelle01** [comment]
Yes, though we can't disable them completely as long as we do not have a solution for the assessment and events field.

**Comment by pcambra** [comment]
Are all operations/clusters using HID now or planning to move shortly?

**Comment by Yaelle01** [comment]
Not all the clusters but the OCHA offices are working on the roll-out in their respective countries. It shouldn't be a surprise to them.

**Comment by Yaelle01** [comment]
In addition to this, the issue I mentioned yesterday is that users who are on auth.humanitarian.id who have never logged into HR.info, can not be 'picked up' in the contact fields (e.g. when you want to give manager rights to people). Try for example this person as a test: 
![image](https://cloud.githubusercontent.com/assets/13348894/11367535/a69a090a-92b4-11e5-84ce-13ded04ffd0f.png)

**Comment by pcambra** [comment]
@Yaelle01 that last bit will be taken care of on #195

**Comment by emmajane** [comment]
I'd like to close this issue as I believe the original issue is resolved, and the follow-up problem of permanently removing contacts is covered in #195. Does that sound right, @pcambra ?

**Comment by pcambra** [comment]
I think I confused #115 with this one.

The subject pending is: " 3. and finally remove the 'Contact' feature from HR.info which means every operation/HQ space by then will be using HID" and I think #217 sort of covers it

**Comment by emmajane** [comment]
@pcambra okay. I'll close this one as the title is 'disable', which is now done (and I'll add a reference in 217 to this issue).
