### ISSUE TITLE
HID contacts on HR.info cluster pages

### ISSUE THREAD

**Issue by Yaelle01** [humanitarianresponse/site#151]
Hi @guillaumev, 

I have noticed that some of the filters of the embedded HID contacts in HR.info Cluster (!) pages do not work. Have a look at https://www.humanitarianresponse.info/en/operations/philippines/education/hid_contacts#table/1? for example. Location, Office and disaster don't seem to work. 

Also, I realized that we need to do some more fine-tuning: 
(1) Take off the key contacts checkbox. 
(2) Take off the group filter for cluster spaces (as it's already filtered by that group already). 

Please find a screenshot attached for better understanding. 

![cluster_contacts_hid_hrinfo](https://cloud.githubusercontent.com/assets/13348894/10668963/e640eb86-78de-11e5-81d2-53ae025bde33.png)

Thank you in advance, 

Yaelle 

FYI @pcambra , @javedyousafzai

**Comment by emmajane** [comment]
@guillaumev it looks like there was work on this about a month ago, but I'm not sure if it was resolved? Can you add an update here about any remaining tasks? Thanks! :)

**Comment by guillaumev** [comment]
The PR was apparently merged, and contacts on cluster pages seem to work, so closing this.

**Comment by pcambra** [comment]
Merged and released indeed :)

**Comment by emmajane** [comment]
\o/
