### ISSUE TITLE
Disable the function 'Add new Dataset' in operational sites

### ISSUE THREAD

**Issue by javedyousafzai** [humanitarianresponse/site#152]
Now that most of the countries CODs are migrated to HDX, we will need to disable the fucntion so that managers or editors in the country offices can't add new datasets since those are maintained on the HDX website.

![image](https://cloud.githubusercontent.com/assets/3966785/10669516/7031fe1e-78e1-11e5-83c5-b31e29c43164.png)

We keep it on low priority for now and maybe waut until HDX migrated all the CODs from HR.info to HDX in phase 3 which should be completed unitl the end of year.

**Comment by guillaumev** [comment]
You can disable the datasets feature in the operation, that should be a quick & easy workaround.

**Comment by javedyousafzai** [comment]
thanks @guillaumev . I will let @pcambra sort it out.

**Comment by pcambra** [comment]
@Yaelle01 do we need to disable the dataset features for all operations/clusters?

**Comment by Yaelle01** [comment]
Yes @pcambra, please disable for all operations and clusters.

**Comment by pcambra** [comment]
Needs to be paired with #229

**Comment by pcambra** [comment]
#247 will disable the datasets feature for all operations and bundles

**Comment by emmajane** [comment]
Completed. Closing the issue. Thanks, @pcambra!
