### ISSUE TITLE
HID Contacts are not loading in Asia Regional website

### ISSUE THREAD

**Issue by javedyousafzai** [humanitarianresponse/site#157]
@pcambra and @humphreymburu!  please see the screebshots captured by Andrej this morning. Asia office has tried several times but the contacts on their HR.info site is not loading. here is the link; https://www.humanitarianresponse.info/en/operations/asia/hid_contacts#table/1

![image](https://cloud.githubusercontent.com/assets/3966785/10752421/51fc18ac-7c89-11e5-9855-11b851aedf1b.png)

Another screenshot;

![image](https://cloud.githubusercontent.com/assets/3966785/10752428/6ecc5370-7c89-11e5-9bfe-8a86db6ba75a.png)

**Comment by pcambra** [comment]
I think this was identified as a cron issue within HID and we can close it?

**Comment by javedyousafzai** [comment]
I would wait a bit longet until Guillaume fix it.

**Comment by javedyousafzai** [comment]
@pcambra and @guillaumev can we close this case if it is solved?

**Comment by guillaumev** [comment]
I'll let @pcambra comment, but for me, this can be closed.

**Comment by pcambra** [comment]
Yes, I think this is fixed
