### ISSUE TITLE
Assessment Registry integration (Interactive Map developed by Troy)

### ISSUE THREAD

**Issue by javedyousafzai** [humanitarianresponse/site#16]
HR.info team needs to integrate the interactive map developed by Troy (intern at FIS, Geneva) in CartoDB visualizing the Assessment Registry content from HR.info. Link to the live map is here; http://un-ocha.github.io/hrinfo/assessment_registry/

**Comment by guillaumev** [comment]
This is now available at https://www.humanitarianresponse.info/en/assessments/map
