### ISSUE TITLE
Manager rights to edit 'custom block' is not working

### ISSUE THREAD

**Issue by javedyousafzai** [humanitarianresponse/site#171]
Gencap focla point with Manager rights is not able to make edits to the 'Custom block'. Although I made her 'Trusted' user in HR.info but she is not able to edit. See the screenshot when she try to edit.

I also logged in with my other email as Manager and I conform, i am not able to make edits.
![image](https://cloud.githubusercontent.com/assets/3966785/10846646/77c07f76-7f11-11e5-82bd-848b7e00d277.png)

Can someone please look into it?
thanks.

**Comment by pcambra** [comment]
"when you are in the Gencap page https://www.humanitarianresponse.info/en/coordination/gencap, click on the 'Customize this page' button and then try to change this 'custom block' and If you are logged in as ,manager, it won't let you change"

**Comment by pcambra** [comment]
@javedyousafzai this was caused by a Full HTML filter in the content, I think is solved now.

https://monosnap.com/file/tBKxYPSD2BzJfAEVXUuoYgmz6c7sPe.png
