### ISSUE TITLE
Map uploaded to Food Security clsuter disappeard

### ISSUE THREAD

**Issue by javedyousafzai** [humanitarianresponse/site#174]
The Food Security focal point in Pakistan office uploaded a map (https://www.humanitarianresponse.info/en/operations/pakistan/infographic/pakistan-earthquake-situation-0) but can't see it under the Maps/Infographics section (
https://www.humanitarianresponse.info/en/operations/pakistan/food-security/infographics) both logged in and anonymous.

**Comment by pcambra** [comment]
We discovered an additional issue where the content created was not made available in panelizer in a reasonable timing.
