### ISSUE TITLE
Web Anaytics error message on Ethiopia site

### ISSUE THREAD

**Issue by javedyousafzai** [humanitarianresponse/site#175]
Ethiopia has reported error when they go to 'Map' tab to get the analytics. Screenshots are attached here.
![image](https://cloud.githubusercontent.com/assets/3966785/10942154/09f906b4-830f-11e5-8b77-71dd03272e65.png)

Also when I click on the 'Settings' I get error - see the screenshot'
![image](https://cloud.githubusercontent.com/assets/3966785/10942183/259b8fc2-830f-11e5-9201-157e144e03e7.png)

**Comment by pcambra** [comment]
Noting down a few issues in piwik, seems that the usersettings report doesnt exist anymore and we need to use another one related with devices:

https://github.com/piwik/piwik/issues/3962
https://github.com/piwik/piwik/issues/7227

**Comment by pcambra** [comment]
I've just pushed a change that will solve the second error of the screenshots, the first error is not always happening, see https://www.humanitarianresponse.info/en/group/node/82/admin/analytics/visitors/map and https://www.humanitarianresponse.info/en/group/node/65/admin/analytics/visitors/map
Maybe related to something like https://github.com/piwik/piwik/issues/6900

**Comment by pcambra** [comment]
This has been fixed with the latest upgrade to 2.16 #161
