### ISSUE TITLE
Not caching HID JSON Output

### ISSUE THREAD

**Issue by guillaumev** [humanitarianresponse/site#187]
I just noticed that HID JSON output, for example:

https://www.humanitarianresponse.info/hid/locations/hrinfo_loc_336

is not cached, because Drupal send "Cache-control: no-cache" headers to Varnish, resulting in relatively slow response times in some HID pages.

I will provide a PR to fix this.

**Comment by pcambra** [comment]
Closing this, feel free to reopen if the issue persists @guillaumev
