### ISSUE TITLE
Linking contact fields to HID

### ISSUE THREAD

**Issue by Yaelle01** [humanitarianresponse/site#195]
# Description

Provide a new field for the content types Assessments and Events which allows HID contacts to be referenced.

# Testing Notes

- if you're admin, you would see the both fields when adding / editing Assessments and Events
- if you're only a group manager / editor, you only see the new field for HID contacts (HR.info contacts cannot be edited or added by group manager / editors). Test this using "masquerade". Notes in the admin guide on how to do this.
- Display-wise, both fields are displayed for everyone

URLs:

- Event add: https://www.humanitarianresponse.info/en/node/add/hr-event
- Assessment add: https://www.humanitarianresponse.info/en/node/add/hr-assessment

# Background

We need to be able to link Assessments and Events to contact records in Humanitarian ID. Equally, HR.info will need to be able to select people, who have never logged into HR.info but are in HID (e.g. one cannot be added to a contact block because the name does not show up in the selection field if the person has not yet logged into HR.info).

After disabling part of the contacts feature and switching the main contacts to Humanitarian ID, we are facing the challenge that there are still contact fields that are pulling the contacts from HR.info. These fields are included in the assessment form as well as the events form.  

On the event creation form it is not known if the space will be a global or local space. As a result, the contacts should be pre-filtered to show only global HID profiles.

On the display of the contact, the linked name of the contact should go to the HID website (global profile); not to an HR.info display of the contact.

Additional follow-up tasks spawned from this one (this list is not maintained):

- completed ~~#215: Audit where groups are still using HR.info contacts~~
- completed ~~#216: Archive old contacts~~
- completed ~~#245: Disable 'Add Contact' link~~
- #217: Remove deprecated contacts code / feature
- #265: Disconnect Assessments and Events from Contacts
- #245: Auto-remove checked out contacts on HID contact blocks

Additional notes:

- when 265 gets in, there will be no old contacts, no field and no display for anybody

**Comment by pcambra** [comment]
@Yaelle01 is this only for the contact fields in Events and Assessments? 
Do we have an idea of the sort of widget that we want? Now the form is just a user autocomplete.
We could keep the autocomplete by name and use HID as a source instead.

**Comment by Yaelle01** [comment]
@pcambra - I think whatever you think is the easiest way to implement this, would be good. Personally,  I think it would be nice to keep the things similar, i.e. maybe use the same autocomplete functions for names in all of HR.info - no matter if you are adding an assessment, event or contact in a block.

**Comment by pcambra** [comment]
Just adding here that we should keep the existing information so a migration process should be done that maps the old contacts with the HID records, when possible

**Comment by pcambra** [comment]
As our conversation in the planning session of december 21st, we don't need a migration just yet.
We need to hide the old contact reference field and display the old contacts just below the new ones.

We also need to export the contacts that are in Hrinfo but not in HID.

After we're sure that everyone is using HID we could revisit and find a solution of those old contacts that will never be on hid.

**Comment by pcambra** [comment]
Script used for the contacts export: 
https://gist.github.com/pcambra/4063f9bd856bb4ce5554

In case we need to run it again, it needs a global and local contact export file from HID so we don't do a lot of requests.

**Comment by emmajane** [comment]
Fields are now available for site admins:

![165-admin-edit](https://cloud.githubusercontent.com/assets/1299320/12090846/4dd4cf66-b2ea-11e5-8489-a43654d33cf7.png)
![165-admin-add](https://cloud.githubusercontent.com/assets/1299320/12090847/4df20b30-b2ea-11e5-983e-fa0f0d869ceb.png)

Still need to test for site managers only seeing the new HID field.

**Comment by emmajane** [comment]
Fields limited correctly for Managers.

![2016-01-04 at 18 51 1](https://cloud.githubusercontent.com/assets/1299320/12097630/8fafa918-b314-11e5-8750-08ac2e6a3bd9.png)
![2016-01-04 at 18 52](https://cloud.githubusercontent.com/assets/1299320/12097631/8fb1705e-b314-11e5-998f-7851fbfed8b7.png)

**Comment by emmajane** [comment]
Both fields display for HR.info and HID contact information. Thanks, @pcambra !

![2016-01-04 at 19 01](https://cloud.githubusercontent.com/assets/1299320/12097809/cd5868f8-b315-11e5-8752-8d4a76134aa2.png)
![2016-01-04 at 19 01 1](https://cloud.githubusercontent.com/assets/1299320/12097810/cd7ad0b4-b315-11e5-8b0f-14a96f6d582b.png)
![Uploading 2016-01-04 at 19.00.png…]()
