### ISSUE TITLE
Disable multisite redirect module

### ISSUE THREAD

**Issue by pcambra** [humanitarianresponse/site#196]
Background:
We have a module called multisite redirect that handles redirects from many places that come from the 1.x migration.
It has quite a large table to decide the redirections and it is being called in every request that hits Drupal.

The goal would be to remove this module completely, for this we have 2 options:

Option 1: Do this gradually, the module has a disabled feature that tracks how often this redirections are used, we can enable it for a while and see if there are some still in place. Then implement this redirections in the Varnish layer, so they will never hit Drupal.

Option 2: The migration happened a year ago and we're issuing 301 for all these pages. We could just disable the feature and see if there's any impact.

**Comment by pcambra** [comment]
@andrejverity @Yaelle01 let me know if you have an input about this.

**Comment by emmajane** [comment]
@pcambra: Let's go ahead and turn on that feature you mentioned in option 1 so that we can start to collect some data about what is happening. Then we'll check back in a week and then again in a month to see if we can just disable the whole thing.

**Comment by pcambra** [comment]
Thanks @emmajane, this went in in yesterday's release, so in a couple of weeks time we can take an informed action on the matter.

**Comment by emmajane** [comment]
\o/

Thanks, @pcambra! I've added a reminder to myself to check back in one week, and again in one month.

**Comment by emmajane** [comment]
@pcambra I have a reminder set to see how this is going... Can you take a look at some point this week?

**Comment by pcambra** [comment]
The poposed solution would be to handle all the multisite redirections in Varnish, such as philippines.humanitarianresponse.info or cod.humanitarianresponse.info and then handle the specific pages in Redirect with a 301. If after a while there's a redirection used massively, we can move those ones to Varnish as well.

**Comment by emmajane** [comment]
This sounds good to me!

**Comment by pcambra** [comment]
There's one task pending: Remove the module from the codebase

**Comment by pcambra** [comment]
Technical task that has been deployed
