### ISSUE TITLE
Adding HID contact blocks on pages

### ISSUE THREAD

**Issue by Yaelle01** [humanitarianresponse/site#198]
Backgroud
I have received an email from our colleagues in Haiti, who have noticed that the HID contact blocks are not enabled on pages (see screenshot).  

![image](https://cloud.githubusercontent.com/assets/13348894/11375185/2c1d39a6-92da-11e5-89fe-3e7f600ba2e0.png)

As an example see also https://www.humanitarianresponse.info/en/operations/haiti/coordination . 

(NB: The feature works well in bundles!)

Action required 

'Enable'  HID contact blocks as content blocks in pages.
  
Completion

Managers can add HID contact blocks on pages. 

FYI @andrejverity

**Comment by emmajane** [comment]
Deployed on 14 December 2015.
