### ISSUE TITLE
Audit watchdog logs

### ISSUE THREAD

**Issue by pcambra** [humanitarianresponse/site#208]
We probably need to create multiple issues while we do this

**Comment by emmajane** [comment]
@pcambra Can you add more details to this when you get the chance so that it can be correctly prioritised? e.g., is this a one-time audit? Are there specific problems you expect to find? Is it a monthly task that needs to be completed as part of routine maintenance? What are the things that you'll be looking for in the audit?

**Comment by pcambra** [comment]
This is to not forget about it. We have many warnings, errors and notices and we should do something about them, probably one in its own issue.

**Comment by emmajane** [comment]
@pcambra "not forgetting" makes it sound like nothing is on fire, which means it might never get prioritised. ;) Let's make a deadline to say every month make a GitHub issue for each of the warnings / errors / notices that should be fixed within 30 days. Would you be able to do the list by 15 Dec?

**Comment by pcambra** [comment]
This came out of checking the logs and looks quite important: https://github.com/humanitarianresponse/site/issues/206 (related with #96 too probably) but it is part of a bigger issue on both logging and having the right environments to test, see also #153 and #197

**Comment by emmajane** [comment]
WINNING! I have setup a monthly recurring task to ask you to review the Watchdog logs. :) I don't mind pestering you and remembering to fit in time once a month for you to be able to do this, but maybe there is a to automate the reminder?

**Comment by emmajane** [comment]
Closing this issue as the follow-up tickets have already been created and a reminder added to check the logs again 15 Dec for new issues.
