### ISSUE TITLE
Import CODs for Kyrgyzstan into HR.info

### ISSUE THREAD

**Issue by Yaelle01** [humanitarianresponse/site#209]
We'd like to launch a new HR.info site for Kyrgyzstan. The CODs are ready at https://data.hdx.rwlabs.org/dataset/kyrgyzstan-admin-level-2-boundaries . Could you import them and let me know once this is done (or of there is an issue with the CODs) ?

**Comment by pcambra** [comment]
https://data.hdx.rwlabs.org/dataset/kyrgyzstan-admin-level-0-boundary-country
https://data.hdx.rwlabs.org/dataset/kyrgyzstan-admin-level-1-boundaries
https://data.hdx.rwlabs.org/dataset/kyrgyzstan-admin-level-2-boundaries

Admin 0 imports correctly but it's creating a single location under Kyrgyzstan, which will be Kyrgyzstan > Kyrgyzstan > .... I don't think this is the desired result

Admin 1 seems to have some export/codifying issues, I've tried to re-export it but haven't been able to make it work, it imports just one record.

Admin 2 seems to work flawlessly which make me think there's a difference between admin 1 and 2.

**Comment by guillaumev** [comment]
My thoughts on this:

Admin 0 has, as a HRPCode, KG417000000, which is wrong: it should only be KG (ie the PCode of the country should be the ISO2 code of the country). Therefore, when importing admin 0, it shouldn't create any new location: it should just update the existing location with PCode = KG. When this is changed, admin 1 will need to be updated with HRParent = KG

What's the error message for the import of admin 1 ?

**Comment by pcambra** [comment]
Thanks to Willem that redid the admin 0 and admin 1 hdx files this has been correctly imported now :)
