### ISSUE TITLE
GA: Configure space variables

### ISSUE THREAD

**Issue by emmajane** [humanitarianresponse/site#212]
In order to accurately collect analytics using Google Analytics, the space variables need to be configured as separate areas within GA.

This effectively is a sub-task of #211 and will need to be completed by someone who is able to administer the GA account settings for HR.info.

**Comment by Yaelle01** [comment]
Suggesting to create a GA account for HR.info with info@humanitarianresponse.info . What are your thoughts on this @emmajane and @andrejverity ?

**Comment by emmajane** [comment]
@Yaelle01 I think it makes sense to create an admin account like this. If needed, we can always use this account to grant limited access to other folks who should not have all access to everything.

**Comment by andrejverity** [comment]
Works for me

**Comment by pcambra** [comment]
Just a note regarding this, we need to clarify what segments do we want. Right now we're sending a concatenated id (;)  of the spaces or bundles (I think we need to consolidate wording) that a node belongs to.

A bit more of information about this, what we want is called "Custom Dimensions" in UGA

https://www.optimizesmart.com/complete-guide-to-dimensions-and-metrics-in-google-analytics/
https://support.google.com/analytics/answer/2709828?hl=en&ref_topic=2709827
https://developers.google.com/analytics/devguides/collection/analyticsjs/custom-dims-mets

Background on not being able to push several values to a single dimension:

http://stackoverflow.com/questions/18403334/universal-analytics-push-multiple-values-for-one-dimension-and-one-pageview
https://groups.google.com/forum/#!topic/google-analytics-analyticsjs/0AtJXDOCQew
https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#customs

We're sending numeric id's which makes our life a bit more complicated, I think we should be sending unique alphanumeric id's instead, which will make the reporting and filtering easier.

**Comment by pcambra** [comment]
Custom dimensions have a limit of 150 bytes, which is not enough to accommodate our documents belonging to multiple (many) bundles. 

Keeping the id only approach, we need to be careful with this when reporting

**Comment by emmajane** [comment]
Deployed on 14 December 2015.
