### ISSUE TITLE
Archive old contacts

### ISSUE THREAD

**Issue by emmajane** [humanitarianresponse/site#216]
Contacts are now managed in HID, not HR.info. In order to remove the underlying code, HR.info contacts need to be archived or migrated to HID.

~~This task relies on the audit in #215.~~ completed

# Tasks

- Open the audit of groups in: https://docs.google.com/spreadsheets/d/1xBv3nvbUedLmTF18fNRam4egT9aeS6_nEsrH-hioXBE/edit#gid=0 for each group there are a number of contacts that need to be "archived" (column B) for groups that are migrated ("done" in column D)
- On the site, go to the old contact page for the group (NOT every group!). For example, Angola. https://www.humanitarianresponse.info/en/operations/angola/contacts. (This is not the HID contact list, it's the old contact list.)
- For each contact on the list, click on the name of the contact, then click Edit.
- Unpublish and save the contact (screen shot below)
- Repeat for each contact
- Once all of the contacts for a group have been unpublished, update the spreadsheet to say the group is "done"

![2015-12-15 at 11 17](https://cloud.githubusercontent.com/assets/1299320/11809291/c4e8e484-a31d-11e5-9960-6519a1c8fe89.png)

**Comment by pcambra** [comment]
We certainly need to clarify about the migration, keeping an archive would be useful (even if it's a csv file) to be in the safe side.

**Comment by humphreymburu** [comment]
@emmajane should I proceed with unpublishing ?

**Comment by emmajane** [comment]
@humphreymburu Yes, please. :) The export is now covered in #246.

**Comment by humphreymburu** [comment]
@emmajane Its done :) and daunting it was.

**Comment by emmajane** [comment]
Wonderful! Thanks, @humphreymburu !

There are still a few operations using HR.info for contacts, but we will create separate tickets for these when Yaëlle has confirmed it's safe to archive the contacts.
