### ISSUE TITLE
Make search box 'type ahead' with Operations list on homepage (Mark's recommendations) 

### ISSUE THREAD

**Issue by javedyousafzai** [humanitarianresponse/site#22]
Need to provide an option where user can type ahead the search term especially the country or operation name, for example, If I am looking for 'Afghanistan' the search box should fill up the rest of the characters when I start typing 'Afg'. See the screenshot below. This will avoid misspelling as users tend to do make this mistake mainly typing the country names.
for those countries.

![image](https://cloud.githubusercontent.com/assets/3966785/8907298/63eb974c-3475-11e5-9415-2aca65080cd5.png)

**Comment by emmajane** [comment]
Site homepage was redesigned to include a list of operations. This list has a "type ahead" box for all operations. Issue no longer relevant, closing.
