### ISSUE TITLE
Update profile headings to match HID

### ISSUE THREAD

**Issue by emmajane** [humanitarianresponse/site#223]
Previously on the HID profiles we used the heading "VOIP" for things like Gchat and Skype. The heading "instant messengers" is now used. We need to update the text we display on HR.info to reflect this change.

Once this has been fixed, I should be able to navigate to:
https://www.humanitarianresponse.info/en/operations/nigeria/hid_contacts#contact/56420804e619c18200c5bbb1 and see "Instant Messengers" above the Skype contact information.

![profile-headings-hid](https://cloud.githubusercontent.com/assets/1299320/11658953/f4fe173c-9dc5-11e5-851d-b5d10f6160b9.png)
![profile-headings-hrinfo](https://cloud.githubusercontent.com/assets/1299320/11658954/f4fe6e9e-9dc5-11e5-9a27-b0974fa34f64.png)

**Comment by pcambra** [comment]
These templates have the labels hardcoded and are not translated, we should figure out how to fix this (templates seem to be plain html), but not sure if we should open a follow up for this.

**Comment by emmajane** [comment]
A follow-up issue for the translation terms is fine, especially as the .pot files are being updated in HID so the translations are not necessarily correct / up-to date right now.

**Comment by pcambra** [comment]
Ok, Not sure how the translations on HID relate with this, let's add that in the follow up.

**Comment by emmajane** [comment]
Deployed. Closing.

**Comment by emmajane** [comment]
Re-opening. "Messengers" was not spelled correctly. Please update the spelling. :)

![2016-01-04 at 19 23](https://cloud.githubusercontent.com/assets/1299320/12098234/c4a275d4-b318-11e5-9b3e-2001c4036d24.png)

**Comment by emmajane** [comment]
Fixed! Thanks, @MartinMaritim 

![2016-01-12 at 09 34](https://cloud.githubusercontent.com/assets/1299320/12258549/cbe1eac6-b90f-11e5-8972-ae9a716ed9a8.png)
