### ISSUE TITLE
Clarify account management language

### ISSUE THREAD

**Issue by emmajane** [humanitarianresponse/site#224]
Currently the account management page says that you can change your email address and password on HID. This is incorrect. Only your password can be changed (this ties into Auth, not the App).

The text on the account page should be updated as follows:

- Replace heading "Change your email address or password" with "Change your password"
- Replace text "Click here to update your email address and password for Humanitarian ID Sign In applications" to "Click here to update your password for Humanitarian ID Sign In applications." link the text "Click here to update update your password", not just the word "here"
- Replace the heading "E-mail address" with "Login e-mail"

Discuss: the email field itself is quite misleading. I don't know if we should hide this, or just update the text (suggestions below). @pcambra opinions, please (when you get the chance).

- Remove the text "A valid e-mail address. All emails from the system will be sent to this address."
- Add (to the end): "To change your login address, please contact our support team: info@humanitarianresponse.info."

![account-page](https://cloud.githubusercontent.com/assets/1299320/11659269/aec792fa-9dc7-11e5-889e-62027f098322.png)
![update-account](https://cloud.githubusercontent.com/assets/1299320/11659270/aed79d9e-9dc7-11e5-9c6f-998913dcf7f6.png)

**Comment by guillaumev** [comment]
We will at some point (hopefully soon) allow users in HID to change their email address, so I wouldn't do this text change, since you will at some point have to revert it...

**Comment by emmajane** [comment]
@guillaumev Is there a ticket in JIRA that we can cross-reference? I searched for a few things, but I didn't see it there...

**Comment by guillaumev** [comment]
I don't think there is a JIRA ticket, but it's definitely in the wishlist

**Comment by emmajane** [comment]
Of course. :) Perhaps when the ticket is created you could cross-reference it here? Thanks!

**Comment by emmajane** [comment]
Confirmed the fix is now live. Thanks! :)
