### ISSUE TITLE
Intermittent file upload issues

### ISSUE THREAD

**Issue by emmajane** [humanitarianresponse/site#232]
When attempting to upload documents, we are sometimes running into problems with a 503 Varnish Error. This has been more obviously visible since installing the throbber for file uploads, as the pop-up error message now appears instead of the process simply hanging.

![503-error](https://cloud.githubusercontent.com/assets/1299320/11739823/8e01fc94-9fee-11e5-823d-48e4a30a2983.png)

- Connection speed of the person uploading the file does not seem to be an issue.
- File size does not appear to be an issue.
- Connections to S1 appear to be more stable than connections to S2.

![image001](https://cloud.githubusercontent.com/assets/1299320/11739820/8dffd9c8-9fee-11e5-8d9f-dce37c5f1400.png)
![image002](https://cloud.githubusercontent.com/assets/1299320/11739821/8e013f7a-9fee-11e5-8d86-a99673e2c75f.png)
![display-cookies](https://cloud.githubusercontent.com/assets/1299320/11739822/8e01e95c-9fee-11e5-8e5c-e8e9d1a3d79d.png)

**Comment by pcambra** [comment]
This is related with #228

**Comment by pcambra** [comment]
https://portal.blackmesh.com/ticket.php?ticket=701020

**Comment by emmajane** [comment]
No longer an issue. Closing.
