### ISSUE TITLE
Remove migrate module and related files

### ISSUE THREAD

**Issue by emmajane** [humanitarianresponse/site#238]
As part of the migration from HR.info 1.x to 2.x we used the module migrate. This has been disabled, and is no longer needed. To ensure it does not cause problems, or become a security risk, the module and related files should be completed removed.

# Tasks

- Ensure we have an up-to-date backup of the database
- Disable and Uninstall the Migrate module
- Delete the migrate module folder from the Git repository

(@pcambra, I'm not sure where the migrate files live ... can you update the ticket with any extra steps?)

**Comment by pcambra** [comment]
We've got the migrate module, migrate_d2d and the hr_migrate one that need to be disabled (if enabled), uninstalled and deleted.
Make sure that the migrate_* tables are gone too.

**Comment by pcambra** [comment]
Technical task that has been deployed
