### ISSUE TITLE
Filter per operation, not query on country

### ISSUE THREAD

**Issue by emmajane** [humanitarianresponse/site#247]
Currently our HDX page is filter is searching for country, which is sometimes not correct.

The number of results returned should match for the example pairs below:

Democratic Republic of the Congo (151 results)

- HR.info: https://www.humanitarianresponse.info/en/operations/democratic-republic-congo/hdx-datasets#table/1
- HDX: https://data.hdx.rwlabs.org/group/cod
- HDX API: https://data.hdx.rwlabs.org/api/3/action/package_search?fq=groups:cod

Colombia (221 results)

- HR.info: https://www.humanitarianresponse.info/en/operations/colombia/hdx-datasets#table/1
- HDX: https://data.hdx.rwlabs.org/group/col
- HDX API: https://data.hdx.rwlabs.org/api/3/action/package_search?fq=groups:col

List of all groups: https://data.hdx.rwlabs.org/api/3/action/group_list
This list is mostly countries (three letter ISO alpha code), except where it's not. e.g., "world", "nepal-earthquake"

**Comment by emmajane** [comment]
Notes from CJ:

> It seems like you may be assuming that there will be a one-to-one relationship between and HRinfo operation and an HDX group.  That may not always be true.   HRinfo may have to have a configurable list of HDX groups to query for a single HRinfo operation.
 
> Also, if you aren't already, be aware that pcodes for the national level (admin 0, country) are a murky business.  In country, they are normally using the two letter ISO 3166-1 Alpha 2 code (IQ = Iraq).  But on HDX we are using the three letter ISO 3166-1 Alpha 3 code (IRQ = Iraq).  I'm not sure about RW or HRinfo.  Because of this (in my experience at least) people normally talk about "country codes" rather than pcodes when we speak about the national level.  Pcodes implies a level of standardization that isn't quite there.

**Comment by emmajane** [comment]
URL we are using:
https://data.hdx.rwlabs.org/api/3/action/package_search?q=null&rows=10&start=0

Example from Dan:
https://data.hdx.rwlabs.org/api/3/action/package_search

Example from CJ:
https://data.hdx.rwlabs.org/api/3/action/package_search?fq=tags:cod%20groups:pak

fq=groups:ABC ==> country
fq=tags:ABC ==> taxonomy terms
q ==> ??? 

Notes from CJ:

> A couple of examples that may help:
> list of datasets (packages) where location (group) = "cod" (3 letter code for DR Congo)
https://data.hdx.rwlabs.org/api/3/action/package_search?fq=groups:cod
> list of datasets with tag = "cod" (Common Operating Dataset) and location (group) = "pak" (3 letter code for Pakistan) https://data.hdx.rwlabs.org/api/3/action/package_search?fq=tags:cod%20groups:pak
> We are currently on CKAN 2.3 and the api documentation is here: http://docs.ckan.org/en/ckan-2.3/api/index.html
> All HDX datasets are tied to a group, which is almost always a country (i.e. Nepal) and may be additionally tied to a group representing a crisis (i.e. "Nepal Earthquake).  At the moment Nepal-Earthquake is the only crisis group we have.  Full list: https://data.hdx.rwlabs.org/api/3/action/group_list

**Comment by pcambra** [comment]
After a conversation with Andrej, this is what we're going for:

If an operation is marked as country, we use the country straightforward.
If it's a region, we check the related operations with this one (backwards) and get the different countries. (see note #1)
This should be exposed as a feature for operations, opt-out.

Notes:

#1 - "Oh, is the other way around, Syria, Turkey cross borders and Jordan cross borders, have as region WoS 12:08
so we could potentially pull from the backwards reference all the countries assigned to those operations that have the current operation as region"

**Comment by emmajane** [comment]
Confirmed on production. Thanks, @pcambra !
