### ISSUE TITLE
Remove Group tab from non-Group nodes

### ISSUE THREAD

**Issue by emmajane** [humanitarianresponse/site#254]
While trying to help update menu items for an operation, I ended up with a permission error. This was caused by landing on a group admin page for a node that is not a group.

For example: 

https://www.humanitarianresponse.info/en/operations/stima/npm-data

![2015-12-23 at 14 29](https://cloud.githubusercontent.com/assets/1299320/11978319/8d565248-a982-11e5-90b9-eddaa2260f51.png)

If I click edit on this node, I can see this is a "page" not a group (or an operation)

![2015-12-23 at 14 30](https://cloud.githubusercontent.com/assets/1299320/11978317/7cecdb7a-a982-11e5-88c7-0948f0eda067.png)

The page has a field that refers to an OG, but the link doesn't take me to the admin screens for that OG. It takes me to: https://www.humanitarianresponse.info/en/operations/stima/npm-data/group
![2015-12-23 at 14 26](https://cloud.githubusercontent.com/assets/1299320/11978194/7120a7b4-a981-11e5-961c-da2eedcfb4c6.png)

If I click on one of the admin links I get the error message "Access denied You are not authorized to access this page."

![2015-12-23 at 14 31](https://cloud.githubusercontent.com/assets/1299320/11978254/eed91510-a981-11e5-80a1-025fe6522b9a.png)

# Potential Solutions

Option 1: Hide the tab on nodes that are not groups.
Option 2: Update the URL for the "Groups" link so that it points to the OG menu screen (might not be possible if the node is assigned to multiple groups).

**Comment by pcambra** [comment]
https://github.com/Gizra/og/issues/95

**Comment by emmajane** [comment]
![2016-01-04 at 13 05](https://cloud.githubusercontent.com/assets/1299320/12090138/e6439ed2-b2e3-11e5-85f6-457307eaad6c.png)
