### ISSUE TITLE
Remove HR.info contact relationship from assessments + events

### ISSUE THREAD

**Issue by emmajane** [humanitarianresponse/site#265]
In order to disable the HR.info Contacts feature ( #195 ), we need to disconnect the relationship between Contacts <--> Assessments and Contacts <--> Events. When this disconnection happens, the field which previously stored a reference to an HR.info contact will no longer work (and should be removed as well).

Additional background: Pedro has exported a list of all contacts ( #246 ), and Yaëlle has confirmed that events + assessments should have "anonymous" entries for old contact information which was previously managed by HR.info contacts (Flowdock - 30 December 2015). Moving forward, all contacts will be managed by referenced to HID.

**Comment by pcambra** [comment]
Related: #251

**Comment by emmajane** [comment]
Admin account is now only able to add HID contacts to assessments and events.
