### ISSUE TITLE
Issue with hid locations pages

### ISSUE THREAD

**Issue by guillaumev** [humanitarianresponse/site#266]
The HID locations pages on HR.info such as:

https://www.humanitarianresponse.info/hid/locations/hrinfo_loc_181

currently display a 404 page not found error.

They should display json data with the admin 1s of each country.

**Comment by emmajane** [comment]
@guillaumev This URL no longer displays 404 for me. Can you please confirm the fix worked for HID?

![2016-01-04 at 13 06](https://cloud.githubusercontent.com/assets/1299320/12090147/18bd813e-b2e4-11e5-8d81-7490f92e97f7.png)

**Comment by guillaumev** [comment]
I can confirm this is working. Thanks @pcambra . Closing this.
