### ISSUE TITLE
Fix wrong geolocations

### ISSUE THREAD

**Issue by guillaumev** [humanitarianresponse/site#28]
Guillaume, please see the message from Troy,

# Yemen
The GPS coordinates for this location is wrong: http://www.humanitarianresponse.info/en/api/v1.0/locations/54548. It is supposed to be on the coast of Yemen, but it is placed in Ethiopia.

# Vanuatu
Here is the location ID for Vanuatu that needs to be fixed: http://www.humanitarianresponse.info/en/api/v1.0/locations/421

He is using the assessments API to visualize the content using CartoDB online maps but there are several cases where the centroid of the polygon does not lie in the right/expected location.

**Comment by Yaelle01** [comment]
Hi @guillaumev , other countries seem to be off, too. How can I check, for example Philippines and Indonesia are odd, too.

**Comment by guillaumev** [comment]
I started looking into this and it won't be easy. To take Vanuatu as an example:

https://www.humanitarianresponse.info/en/location/vanuatu

The centroid calculated with HR.info is the same as the centroid calculated with QGIS, which means that there is an issue with the underlying library calculating centroids (suspecting it's because Vanuatu is a multipolygon rather than a single one), so it won't be an easy fix...

**Comment by Yaelle01** [comment]
I see. So it's probably an issue for most of the 'islands countries'? I may just make a reference on the website (http://humanitarian.id/check-in-map/) then.

**Comment by guillaumev** [comment]
@Yaelle01 Yes, I believe the issue should be only for multipolygons. Maybe someone from HDX could have a look at this and see if they have an idea...

**Comment by Yaelle01** [comment]
Hi @guillaumev , I briefly talked to CJ. I think he suspects the same as you: Either CartoDB is referring to a bounding box or perhaps but less likely, a balance point. He says, the only thing he imagines would be to add a point for every single country in HR.Info, a human-created centre-point. Not sure where this puts us but I tried my best to summarize this intellectual conversation.

**Comment by emmajane** [comment]
What's the status of this? I'm not sure who currently uses the Assessment API from our site... Will we get new boundaries to improve the data, or is it enough to just give a link to the the website (per Yaëlle's suggestion)?

**Comment by emmajane** [comment]
Emailed CJ and Yaëlle to confirm the status 31 December 2015.

**Comment by emmajane** [comment]
I have followed up with Yemen and confirmed there is a known issue in their admin boundaries dataset. This is not an HR.info error, but rather a problem with the source dataset. It would be up to the countries to provide a corrected dataset that we could then import. Closing this issue as there is no fix needed from HR.info's side.
