### ISSUE TITLE
Cannot upload files

### ISSUE THREAD

**Issue by emmajane** [humanitarianresponse/site#284]
There is an error when attempting to upload files attached to the content type Documents.

Sample URL: https://www.humanitarianresponse.info/en/node/add/hr-document

![2016-01-13 at 11 12](https://cloud.githubusercontent.com/assets/1299320/12291331/de077b80-b9e6-11e5-920f-d0488b7a4df9.png)

As reported by Mark Pryce:

![upload-error-2](https://cloud.githubusercontent.com/assets/1299320/12291367/18fc869a-b9e7-11e5-8ea8-44665ede4c01.png)
![upload-error-1](https://cloud.githubusercontent.com/assets/1299320/12291368/18fe5aa6-b9e7-11e5-91e1-8304087e6fae.png)

**Comment by pcambra** [comment]
This was related with ticket 709562 in blackmesh. When they did the core dumps to investigate an unrelated problem, they left the container with no space available. Moving these dumps elsewhere fixed the issue.
