### ISSUE TITLE
Enable piwik geolocation in hrinfo webserver

### ISSUE THREAD

**Issue by pcambra** [humanitarianresponse/site#286]
From Serban's comments: 

"piwik seems to work now, but before jumping on ticket: all visitors in the log seems to originate from the BM HAProxy load balancer (10.5.68.1). This is because the web server that piwik takes the logs from is not configured to log the real ip from either X-Forwarded-For or X-Real-IP headers."

http://piwik.org/faq/how-to-install/faq_98/

Alternatively on the hrinfo webserver:

"on apache 2.2.15 (assuming that is the one you are using): use mod_rpaf (see http://old.drupion.com/resources/downloads/mod-rpaf)
on apache 2.4 (assuming you do have one): use mod_remoteip (see apache docs)"

**Comment by pcambra** [comment]
This has been done at varnish level and pull requests have been created in the rw-env repo to make the change persistent.

**Comment by emmajane** [comment]
PR has not been rolled in yet on rw-env; I have followed up with Sarah to understand more about that process. Closing this ticket and I will follow-up in the other repository.
