### ISSUE TITLE
Bulk disable all OG Feature for HR.info Contact

### ISSUE THREAD

**Issue by emmajane** [humanitarianresponse/site#291]
The OG Feature for Contacts is turning back on after having been manually disabled. We need a way to bulk disable across all operations (groups?).

Although some operations are still using HR.info contacts, it is acceptable to disable the OG Feature for all operations. (Yaëlle has confirmed this. Emma will be monitoring support.) For reference, these are the groups: Afghanistan, occupied Palestinian territory, South Sudan, Sudan, Syria, Turkey Cross-border, Whole of Syria, Yemen.

**Comment by emmajane** [comment]
I was looking at the OG settings for features and saw that HR.info contacts is still enabled by default for new groups. Could this be affecting anything?

**Comment by emmajane** [comment]
Default "on" may also be affecting new HDX menus.

**Comment by pcambra** [comment]
The process ran in this past release didn't fix the duplicated contacts issue. Need to review why and find an alternative solution.

**Comment by emmajane** [comment]
Duplicate "contact" menu items have finally been magicked away. Thanks, pedro!
