### ISSUE TITLE
Fix missing thumbnails

### ISSUE THREAD

**Issue by emmajane** [humanitarianresponse/site#313]
After the GlusterFS migration, we are missing many thumbnails for the content type Documents for many spaces including Pakistan, Yemen, and Afghanistan websites. On the affected pages, it appears as though the image URL has only the base URL, and not the complete file name.

![2016-02-02 at 08 15](https://cloud.githubusercontent.com/assets/1299320/12743330/30d94cfa-c985-11e5-9922-167765bd97d7.png)

# Tasks

- Confirm why some document listing pages are not displaying images.
- If necessary, bulk regenerate thumbnails for Documents -- This will cause performance issues while the thumbnails are being regenerated.
- Test URLs known to be affected:
  - https://www.humanitarianresponse.info/en/operations/yemen/documents
  - https://www.humanitarianresponse.info/en/operations/afghanistan/documents
  - https://www.humanitarianresponse.info/en/operations/pakistan/documents
- Follow-up with the IMOs to confirm thumbnails are now appearing throughout the site. (Emma will complete this task.)

**Comment by pcambra** [comment]
Fixed

**Comment by emmajane** [comment]
Great! Thanks! :) Can you confirm what the fix was?

**Comment by pcambra** [comment]
I guess some of the images (private ones mostly) didn't refresh properly after the glustefsddon, I forced the recreation of those and cleared cache.
