### ISSUE TITLE
Decommission Dataset API

### ISSUE THREAD

**Issue by emmajane** [humanitarianresponse/site#324]
Per our [blog post about the HDX integration](https://www.humanitarianresponse.info/en/about/article/bring-data-we-now-show-datasets-hdx), we are now ready to stop publishing the Dataset API.

This API is currently available at:
https://www.humanitarianresponse.info/en/api/v1.0/datasets

To be polite, we should redirect requests for that URL to: https://data.hdx.rwlabs.org/faq#body-faq-HDX_API (confirmed by CJ).

**Comment by pcambra** [comment]
Does this mean that we can decommission the datasets themselves in the site as well?

**Comment by emmajane** [comment]
Yes, please! :)

**Comment by emmajane** [comment]
Redirect works! Thanks, Pedro.
