### ISSUE TITLE
assigning multiple organizations to document with more clarity

### ISSUE THREAD

**Issue by javedyousafzai** [humanitarianresponse/site#33]
Guillaume, See the  messages below from Afghanistan where they wanted to add e.g. tow org unicef and ocha to the content, I explained to them that its is possible by putting comma "," and then typoe another org, which works but their feedback is that its not intuitive so I am adding a case with low priority for now.

![image](https://cloud.githubusercontent.com/assets/3966785/8980120/9a44db7e-36ae-11e5-9d66-4f4e2f245f75.png)

They as asking that it should appear like the 'Coordination Hub' where everytime you add new item, it becomes a box.

**Comment by javedyousafzai** [comment]
after adding this issue in Git, couple of hours later Keith from ROSA added a case in Atrium about the exact same issue :). Here is the link to Atrium http://atrium.humanitarianresponse.info/humanitarian_response/node/4716.

I guess we will have to prioritize it now.

**Comment by guillaumev** [comment]
This is working in my local environment, so I just merged this in the dev branch.

**Comment by guillaumev** [comment]
Now available in production. Closing this.
