### ISSUE TITLE
Adapt the main stats process to the latest piwik version

### ISSUE THREAD

**Issue by pcambra** [humanitarianresponse/site#334]
Now we're getting "Error: The parameter 'space_id' isn't set in the Request, and a default value wasn't provided." on the piwik site

**Comment by pcambra** [comment]
Added a PR in the piwik plugin https://github.com/humanitarianresponse/piwik_plugin/pull/7

**Comment by emmajane** [comment]
I can now visit https://stats.humanitarianresponse.info without getting an error. Stats summary is returned (as expected). \o/
