### ISSUE TITLE
Enable sorts for dynamic content panes

### ISSUE THREAD

**Issue by emmajane** [humanitarianresponse/site#335]
Recently one of the content managers noticed that the sorted list of documents on the page /documents and the content pane "latest documents" doesn't always match. This is due to a difference in the default sort order for both lists.

Sample URLs:

- https://www.humanitarianresponse.info/en/operations/nigeria -- content pane at the bottom -- uses post date, and then publication date to sort
- "view more" link leads to: https://www.humanitarianresponse.info/en/operations/nigeria/documents which uses only publication date to sort the list

# Tasks

- Expose the "sorts" as well as the "filters" in all the dynamic panes.
- confirm the new "sort" option is available on the content pane for "latest documents" on https://www.humanitarianresponse.info/en/operations/nigeria

![nigeria 7c humanitarianresponse 2016-02-10 16-22-16](https://cloud.githubusercontent.com/assets/1299320/12953829/01c2a552-d014-11e5-83ae-0de8b0252d8b.jpg)

**Comment by emmajane** [comment]
@pcambra looking at https://www.humanitarianresponse.info/en/operations/nigeria "latest documents" I don't see a "sort by" option. Can you confirm where this should appear? Thanks! :)

![2016-02-16 at 16 03](https://cloud.githubusercontent.com/assets/1299320/13082049/f3eedc7c-d4c6-11e5-9414-6b92daf4968d.png)

**Comment by pcambra** [comment]
Had forgotten to revert the relevant feature, should be displaying now

**Comment by emmajane** [comment]
Fixed! Thanks, @pcambra !

![2016-02-16 at 16 13](https://cloud.githubusercontent.com/assets/1299320/13082364/50a20902-d4c8-11e5-8595-2bea238926a5.png)
