### ISSUE TITLE
Re-index maps / infographics

### ISSUE THREAD

**Issue by emmajane** [humanitarianresponse/site#340]
When we're on the CAR website, setting the filters in the map repository to for example Org: OCHA and Type: Humanitarian Snapshot, we cannot find all the content that has been uploaded and tagged with these attributes. Here is one that doesn't seem to show up in the filtered search: 

https://www.humanitarianresponse.info/fr/operations/central-african-republic/infographic/humanitarian-access-snapshot-october-2015

Second example: When I search for an OCHA Infographic that is a funding graph, I can find it if I only put in the org filter, but if I add the map type filter, it doesn't show up anymore. https://www.humanitarianresponse.info/en/operations/central-african-republic/infographic/fts-update-novembre-2015

https://www.humanitarianresponse.info/en/operations/central-african-republic/infographics/table/organizations/united-nations-office-coordination-humanitarian-affairs?search=&page=2v

filtered page: 
![img_15022016_100339](https://cloud.githubusercontent.com/assets/1299320/13043921/2156f1fe-d3c3-11e5-836e-898651fbbbe2.png)

This may be related to: https://github.com/humanitarianresponse/site/issues/282

When the files have been re-indexed, and this file is correctly appearing, notify Yaëlle.

**Comment by MartinMaritim** [comment]
@emmajane the infographic https://www.humanitarianresponse.info/fr/operations/central-african-republic/infographic/humanitarian-access-snapshot-october-2015 does show up in my dev, so I can confirm that this is indeed an indexing issue.

**Comment by emmajane** [comment]
Note: when I looked today at: https://www.humanitarianresponse.info/en/operations/central-african-republic/documents the filter "Map" is missing from the left sidebar. Is it possible this was in a feature that was reverted during these updates?

**Comment by MartinMaritim** [comment]
@emmajane The 'Map' filter is configured to show only in the infographics page. The documents page would display the 'Document Type' facet instead.

**Comment by emmajane** [comment]
@MartinMaritim within the document type facet, I am not seeing the option to filter by the document type "Map / Infographic". Maybe this will re-appear after the re-indexing is complete? But right now I don't see how I would locate https://www.humanitarianresponse.info/en/operations/central-african-republic/infographic/snapshot-acc%C3%A8s-humanitaire-september-2015 via the filters...

**Comment by MartinMaritim** [comment]
@emmajane, sorry I didn't come out clearly, what I meant was that the 'Map' filter can't display on the documents page https://www.humanitarianresponse.info/en/operations/central-african-republic/documents, you will find it on the infographics page instead https://www.humanitarianresponse.info/en/operations/central-african-republic/infographics.

**Comment by emmajane** [comment]
The document that was previously missing is now available via the filtered search.

![2016-02-25 at 08 03](https://cloud.githubusercontent.com/assets/1299320/13313497/52bda8de-db96-11e5-9541-1ab39cfd338c.png)
