### ISSUE TITLE
HID disaster filters should not use reliefweb id

### ISSUE THREAD

**Issue by pcambra** [humanitarianresponse/site#351]
Disaster filter in this screen:

https://www.humanitarianresponse.info/en/operations/fiji/hid_contacts#table

Should use the hrinfo filter instead of the rwint one:

https://www.humanitarianresponse.info/en/operations/fiji/hid_contacts#table/1?disasters_remote_id=rwint%3A30871

https://www.humanitarianresponse.info/en/operations/fiji/hid_contacts#table/1?disasters_remote_id=hrinfo%3A19401

**Comment by emmajane** [comment]
This appears to have been an issue from two GLIDE numbers being created. ReliefWeb later linked the Tonga and Fiji GLIDE numbers in their API (http://api.reliefweb.int/v1/disasters/30871). The links above do not result in a filtered list; however, if you use the UI filter, you now correctly get a subset of people who are tagged with Winston.
