### ISSUE TITLE
Improve perforrmance to load menus

### ISSUE THREAD

**Issue by guillaumev** [humanitarianresponse/site#372]
Currently, loading menus takes a long time, because we have about 20 000 + menu items stored in a menu which is connected to the og_menu_single Drupal module, and correspond to the horizontal menu items of Humanitarianresponse. 
Most of these menu items are standard and follow the status of the og features which are active.

The idea is to therefore generate these menu items dynamically in a custom block based on the status of the og_features, and remove the 20 000 + menu items, which should have a positive impact on performance.

Notifying @emmajane and @Yaelle01

**Comment by emmajane** [comment]
This is a duplicate issue of #241.

Previously when we had discussed this, it was not appropriate to remove the custom menu links from the horizontal menu without first reviewing each of the spaces. Several have custom menu links that should not be removed without first consulting with the group.

**Comment by guillaumev** [comment]
Closing this as a duplicate of #241
