### ISSUE TITLE
Admin/Manager Interface in Cyrillic

### ISSUE THREAD

**Issue by Yaelle01** [humanitarianresponse/site#373]
@guillaumev and @emmajane , I've noticed that some of the admin/manager interface shows up in Cyrillic rather randomly. I am creating this ticket (didn't find an existing one - maybe didn't search properly) to track where this happens by adding screenshots whenever I come across it. Not a high priority but may be useful to track where it's happening.

![image](https://cloud.githubusercontent.com/assets/13348894/13609031/a0e8398c-e557-11e5-812d-33a8d0152104.png)

FYI @andrejverity

**Comment by emmajane** [comment]
This is a duplicate of #307
