### ISSUE TITLE
Integrate related content in HR.info

### ISSUE THREAD

**Issue by guillaumev** [humanitarianresponse/site#41]
Follow up from https://atrium.humanitarianresponse.info/humanitarian_response/node/4491

**Comment by guillaumev** [comment]
@MartinMaritim When I add the above commit to the hr_datasets module, do a drush cc all and then try to access en/operations/nepal/hdx-datasets, I get an Access denied. Could you check ?

**Comment by MartinMaritim** [comment]
@guillaumev I will have a look. Thanks

**Comment by MartinMaritim** [comment]
@guillaumev I have just looked into this and it seems to be a CORS issue(https://en.wikipedia.org/wiki/Cross-origin_resource_sharing). Just tried using http://cors.io/ in my local and it seemed to work. I guess this is something ReliefWeb have to allow on their end?

**Comment by guillaumev** [comment]
![hrinfo-41](https://cloud.githubusercontent.com/assets/90224/9054716/90ae2136-3a84-11e5-8139-f27a4a12ac04.png)

Above is the screenshot of what I see on my local. I don't think this is a CORS issue, the javascript isn't even loaded...

**Comment by MartinMaritim** [comment]
Ok I will look into it further. You seem to be getting a different result from mine. Kindly have a look at my screenshots.
![screenshot 1 - network](https://cloud.githubusercontent.com/assets/3490890/9054870/38daea16-3a8e-11e5-8fbf-972ce99ece83.png)
![screenshot 2 - error](https://cloud.githubusercontent.com/assets/3490890/9054874/3f7cc7a4-3a8e-11e5-98c4-382cd2ec7ac9.png)

**Comment by guillaumev** [comment]
Just tested this and here are a few issues:

1. The space menu still appears in the left sidebar in both the datasets and jobs pages (see screenshot)
1. The dataset title column does not seem to display the "human title" of the dataset
1. Ideally, the search bar should be integrated in the search bar of the top right corner, with the title "Search Datasets" or "Search Jobs" (see https://www.humanitarianresponse.info/en/operations/nepal/hid_contacts)

![hdx-datasets](https://cloud.githubusercontent.com/assets/90224/9220163/9b730cbe-40e0-11e5-8bf3-a8f2327d00ee.png)

**Comment by MartinMaritim** [comment]
Hi @guillaumev. Will work on the changes. Cheers,

**Comment by guillaumev** [comment]
Here are the results of integration: 

* http://staging.hrinfo.568elmp02.blackmesh.com/en/operations/afghanistan/jobs
* http://staging.hrinfo.568elmp02.blackmesh.com/en/operations/afghanistan/hdx-datasets

@Yaelle01 @andrejverity Feel free to comment and tell me if you think it's ready for production

**Comment by javedyousafzai** [comment]
@guillaumev, after implementing this, user will be able to add the pages for Funding, jobs and datasets right? Are we providing some interface which I can document to guide them on how to add those content in the operation websites?

**Comment by Yaelle01** [comment]
Just out of curiosity, there is no way to filter meta-data as we used to in the CODs, e.g. admin boundaries 1-4?

**Comment by guillaumev** [comment]
It SHOULD be possible, assuming HDX provides this possibility in their API, but that's the kind of thing that needs to be defined: which filters do we want to have, and which columns ?

**Comment by pcambra** [comment]
Seems we need these filters https://files.gitter.im/humanitarianresponse/PoN1/blob

**Comment by andrejverity** [comment]
These filters would be nice - assuming we can access them all.

1) Lower priority ones would likely be License & Date Range.  Location depends on what is in their Location (if only country, then we should show it pre-filtered to our given Operation OR not show it when we are inside an HR.info operation)

2) For Tags, i would suggest we say "HDX Tags"

**Comment by javedyousafzai** [comment]
@MartinMaritim please note those filts and see If you can work on those for now.

**Comment by pcambra** [comment]
After our call with CJ, probably we want to swift from the info we're listing (name + url) to a richer content listing, see this issue https://github.com/OCHA-DAP/hdx-ckan/issues/3022#issuecomment-136416263 and this screenshot: https://cloud.githubusercontent.com/assets/8006323/9583239/29a1286c-4fd8-11e5-8748-41e8751054d5.png

Also, HDX is rolling a new set of filters that we could use.

**Comment by MartinMaritim** [comment]
![hdx-datasets](https://cloud.githubusercontent.com/assets/3490890/10783229/306b910c-7d67-11e5-9398-97b30922a267.png)
This is how it looks now ...

**Comment by andrejverity** [comment]
A couple quick comments:
1) Perhaps we can hide the URL (it is not so pretty). Either we a) turn the
Title into a link which would also save some space, or b) we put a generic
word - e.g. Link
2) Could we change the date format to DD-MMM-YYYY

**Comment by MartinMaritim** [comment]
@andrejverity thanks! 
1. Turning the title into a link seems to be a good option, will do that then send a screenshot.
2. Noted, will do.

**Comment by pcambra** [comment]
Reviewing this change, @andrejverity comment about changing the date format to DD-MMM-YYYY is still pending. Now is MM-DD-YYYY.

I think we can add a followup to this issue to make the rows richer, as mentioned in https://github.com/humanitarianresponse/site/issues/41#issuecomment-148318824

And a different one to add more filters https://github.com/humanitarianresponse/site/issues/41#issuecomment-143699520

**Comment by andrejverity** [comment]
Well, as a very minimum, let's make sure we get the date format done: DD-MMM-YYYY.

Fancier is always nice....but remember that recommendations from HDX come from a group that has several technical staff & a dedicated designer. We have a long to-do list.

**Comment by pcambra** [comment]
Agreed, that's why I want to split this to be able to do priorities with the other (fancier?) stuff

**Comment by pcambra** [comment]
Added the two new issues above so we can close this earlier and move on.

**Comment by emmajane** [comment]
@pcambra thanks for the follow-up issues!

@MartinMaritim Can you provide a summary of what still needs to be done? (Or maybe it's finished and just waiting for review?)

**Comment by MartinMaritim** [comment]
@emmajane this was split into #202 and #203, and the other part already merged to dev. I believe we can close this. Thanks.

**Comment by emmajane** [comment]
Great! Thanks, @MartinMaritim ! :)
