### ISSUE TITLE
Displaying week and day events on smartphone screen

### ISSUE THREAD

**Issue by humphreymburu** [humanitarianresponse/site#45]

**Comment by pcambra** [comment]
It's looking good, only noticed a couple of things: http://monosnap.com/image/g7IM4haEj0xr7QgBKyhu94WdfDfgbY.png

Can we make something with the navigation arrows of the top? (that's on 320 width)
The apply button doesn't have enough space.

**Comment by humphreymburu** [comment]
@pcambra I made the changes you requested check if its good to go.

**Comment by javedyousafzai** [comment]
@humphreymburu bravo :)

Can we adjust the arrow for Week and Day view? See the screenshots;
**Week view:**
![image](https://cloud.githubusercontent.com/assets/3966785/10451738/4bbbe00e-71a2-11e5-8734-d002bedd84cc.png)

**Day view;**
![image](https://cloud.githubusercontent.com/assets/3966785/10451762/760bbb4a-71a2-11e5-9b42-7ff0c6e339e0.png)

**Comment by emmajane** [comment]
@humphreymburu Can you let me know what's happening with this issue?

**Comment by emmajane** [comment]
Looks good on prod. Thanks, @humphreymburu !

![img_0657fc081cf5-c75e-4a53-9c9e-20b9a9782415](https://cloud.githubusercontent.com/assets/1299320/12258520/9b88ec12-b90f-11e5-8322-497ca84fd010.PNG)
