### ISSUE TITLE
Calendar entries

### ISSUE THREAD

**Issue by Yaelle01** [humanitarianresponse/site#47]
I have noticed that when creating a calendar event, the end date does not automatically update to the same date as the starting date. Is there a quick fix to have both dates in line with each other (and change the end date if applicable of course)?

![image](https://cloud.githubusercontent.com/assets/13348894/9172989/6f7d56f6-3f77-11e5-850c-9a439f49d80d.png)

**Comment by MartinMaritim** [comment]
This change is already available in dev. Closing, feel free to re open if needed.
