### ISSUE TITLE
Google Apps - Message bounces. 

### ISSUE THREAD

**Issue by Yaelle01** [humanitarianresponse/site#48]
Hi guys, I've received the feedback below from the Education Cluster in Mali, using the Google Apps account. Can one of you get back to her and sort it out? I have been trying to assist, but it may just exceed my technical knowledge. I've found this but don't know how to do it: https://support.google.com/a/answer/168383?hl=en

Can one of you get in touch with her (Mali Education <mali.edu@humanitarianresponse.info>)

Email from Sarah: 

I have been sending messages to around 500 email addresses from gmail for
months with no where near this many bounces. Not sure what the deal is. I
forwarded the same messages to partners from the old gmail account and
didn't receive the same error messages. Perhaps gmail send it to their
spam, but for the UN and NGO partners, they better get through. I wouldn't
be surprised if we're on some blacklist since I forward so many different
things from all over the place... Sad when IM'ing gets confused with
spamming!

**Comment by emmajane** [comment]
@Yaelle01 is this still a problem?

**Comment by emmajane** [comment]
@Yaelle01 I'm going to close this ticket as it's not technically a problem with the site (it sounds like she needs a distribution list for bulk emails...). Let me know if you want me to follow-up with Sarah.
