### ISSUE TITLE
Add a checkbox to keep disasters out of sync

### ISSUE THREAD

**Issue by guillaumev** [humanitarianresponse/site#50]
Some disasters, like for example https://www.humanitarianresponse.info/en/disaster/fl-2015-000017-pak, need to be kept out of sync with Reliefweb (because we are modifying the title manually for example). Currently, this is handled in the hr_disasters.module file, directly hardcoded.

A much better solution would be to add a checkbox to the Disaster content type to keep the disaster out of sync, which is why I'm creating this issue.

**Comment by emmajane** [comment]
In the original issue, it said that there were already some disasters that needed to be kept out of sync. However, when I go to that node, I see the checkbox is NOT enabled. I believe it should be.

@MartinMaritim How was this accounted for? It seems like you might still need to go to the production server and enable this checkbox for the items that used to be hardcoded, but I'm not sure how it was all setup... please confirm.

![2016-01-25 at 15 20](https://cloud.githubusercontent.com/assets/1299320/12555069/46673104-c377-11e5-9c93-ecfa67eb3d73.png)

**Comment by MartinMaritim** [comment]
Thanks for this @emmajane. You are right, I will go ahead and make the necessary changes.

**Comment by MartinMaritim** [comment]
@emmajane I have edited the disasters that needed to be kept out of sync with RW. Thanks.

**Comment by emmajane** [comment]
Checkbox is enabled on prod. Thanks, @MartinMaritim !
