### ISSUE TITLE
Investigate HR.info platform to improve site performance

### ISSUE THREAD

**Issue by javedyousafzai** [humanitarianresponse/site#56]
Any comments, discussion needed to investigate or other suggestion for speed improvements, please add them here.

**Comment by guillaumev** [comment]
Improved the varnish configuration by setting a cache of 60 seconds and a grace period of 24 hours. Still needs to be improved in the longer term by increasing the memory available for Varnish, but this is something that needs to be coordinated with Phase2/Blackmesh (waiting for an answer from them)

**Comment by pcambra** [comment]
Here we have a list of content

**Comment by javedyousafzai** [comment]
Great. Any chance to export those in xls or csv?

**Comment by pcambra** [comment]
I can certainly add that, let me know if you need more information or details on the records

**Comment by javedyousafzai** [comment]
If you can add 'Operation', 'content type' and the size of content (document/map), that would be very helpful.

**Comment by javedyousafzai** [comment]
I would like to start contacting the field IMOs to have call sessions with them and recors the number of actiosn the do, so we can capture some good feedback for us and start working on improving the speed issues. What is the status of the list now?

**Comment by pcambra** [comment]
@humphreymburu just noticed that the exports are only affecting the first 10 files:

https://monosnap.com/file/uBGpt2EMikA4R1cLdmNVlofl3Jz5VR.png

Could you fix that?

**Comment by humphreymburu** [comment]
Ok @pcambra Done

**Comment by pcambra** [comment]
I think this needs feedback, @javedyousafzai was verifying which were the most active users to contact them for feedback on where to focus performance improvements, maybe @Yaelle01 can take over this.

**Comment by emmajane** [comment]
Closing in favour of the label "[performance](https://github.com/humanitarianresponse/site/labels/performance)".
