### ISSUE TITLE
reduce the size of the thumbnail with no image in Document section

### ISSUE THREAD

**Issue by javedyousafzai** [humanitarianresponse/site#58]
See the screen-shot below, when I am browsing the documents in the page https://www.humanitarianresponse.info/en/operations/iraq/documents?search=&page=5 and there is no image for thumbnail, it gets displaced very big and also takes extra space for the card compared to those docs which has image/thumbnail.

Can we reduce it so it remain consistent designwise.

![image](https://cloud.githubusercontent.com/assets/3966785/9380350/056fad98-4730-11e5-9d2e-52c619e81136.png)

**Comment by pcambra** [comment]
@humphreymburu @MartinMaritim could you handle this one?

**Comment by humphreymburu** [comment]
@pcambra Let me handle that one.

**Comment by javedyousafzai** [comment]
@humphreymburu do we need to close this case now?

**Comment by humphreymburu** [comment]
@javedyousafzai We can close it.
