### ISSUE TITLE
'Map tab' on Assessment page in HR.info

### ISSUE THREAD

**Issue by javedyousafzai** [humanitarianresponse/site#69]
Pedro, can you please add a tab 'Map' in the page https://www.humanitarianresponse.info/en/assessments to show interactive assessment map 'https://www.humanitarianresponse.info/en/assessments/map'.

**Comment by pcambra** [comment]
Just to clarify, after a conversation with @javedyousafzai. What we want here is to display the global map from http://un-ocha.github.io/hrinfo/assessment_registry/ in a tab of the https://www.humanitarianresponse.info/en/assessments page, but hiding the drupal default facets and filters, plainly inserting the map.

**Comment by javedyousafzai** [comment]
@pcambra! yes this is how we would need to display the 'assessment' map.

**Comment by javedyousafzai** [comment]
@pcambra I believe this is done now no?

**Comment by pcambra** [comment]
This will be released today

**Comment by javedyousafzai** [comment]
OK I am closing this case.
