### ISSUE TITLE
Jenkins Script  for monthly stats in HR.info

### ISSUE THREAD

**Issue by javedyousafzai** [humanitarianresponse/site#70]
@guillaumev developed the Jenkin script for us some months ago to deal with producing monthly stats and we run it at the end of every month to get the stats (visits, in-country visits, and content type doanlaods). 
See the Google doc where I have listed how to run it and get the figures. https://docs.google.com/document/d/1DlCT4ge53y138HlPggL_eERdbNadYFXIhq3KX3opLdA/edit?usp=sharing 

Now we are trying to run it today for the August month, but its nor running. @pcambra can you please help? 

Please note that we need those stats for the end of Aug month. 

@guillaumev would be great If you can provide some help/guide to Pedro for the 'Jenkins' so he can troubleshoot.

**Comment by javedyousafzai** [comment]
the iss, after providing the data parameter for month, it runs but after few seconds and not produce the actual figures. see for example Build 83 in the screenshot below;

![image](https://cloud.githubusercontent.com/assets/3966785/9547880/85e0e8d4-4d9d-11e5-9da2-51dee37a59d5.png)

**Comment by javedyousafzai** [comment]
Is this in production now ?

**Comment by javedyousafzai** [comment]
@pcambra do you want to close this case OR there is anything peding?

**Comment by pcambra** [comment]
I think this is done, yes.
