### ISSUE TITLE
Active/inactive operation from HR.info into HID

### ISSUE THREAD

**Issue by javedyousafzai** [humanitarianresponse/site#77]
@guillaumev and @pcambra, after I got the operations list from @martin, there are total of 251 operations in HR.info, (75 active), (171 inactive) and 5 blank - no status). right now.

HID shows only active operations where responders can check-in to, but Andrej Yaelle want to show all the 'active/inactive' operations.

In HR.info, we are exposing only 'active' operations - so we need to change the API part so that it can expose all the operations. @pcambra, you may want to check with @guillaumev on this bit as he knows the history.

**Comment by guillaumev** [comment]
@javedyousafzai the HR.info API exposes both active and inactive operations, it's just that HID, for now, only takes active operations, so there is no work needed on this from the HR.info side

**Comment by javedyousafzai** [comment]
ah OK thanks @guillaumev

**Comment by javedyousafzai** [comment]
@guillaumev do you want to close this case?

**Comment by guillaumev** [comment]
@javedyousafzai Thanks for the reminder, I'm closing it.
