### ISSUE TITLE
Invalid operations in HR.info API

### ISSUE THREAD

**Issue by guillaumev** [humanitarianresponse/site#78]
While synchronizing all of the operations with HID, I found issues with the following operations.

Missing country:
* Japan: https://www.humanitarianresponse.info/en/api/v1.0/operations/17448
* Jordan Cross-border: https://www.humanitarianresponse.info/en/api/v1.0/operations/66620
* Macedonia: https://www.humanitarianresponse.info/en/api/v1.0/operations/70691
* Saint Helena: https://www.humanitarianresponse.info/en/api/v1.0/operations/70719

Countries duplicated:
* Jamaica: https://www.humanitarianresponse.info/api/v1.0/operations?filter[label]=Jamaica
* Greece: https://www.humanitarianresponse.info/api/v1.0/operations?filter[label]=Greece

**Comment by Yaelle01** [comment]
@javedyousafzai - We have also noticed that DRC and CAR get pulled in in French.  Can you fix it?

**Comment by javedyousafzai** [comment]
@guillaumev I have assigned countries values to the Macedonia, Saint Helena and Japan. 

For Jordan, we have two entries, 1) https://www.humanitarianresponse.info/en/operations/jordan-cross-border/ where no country is assigned to it and 2) https://www.humanitarianresponse.info/en/operations/jordan where country is assigned to it but 'inactive', which one we should use now? option 1, I believe? @guillaumev ??

For duplicate countries; I have removed Jamaica and Greece.

**Comment by javedyousafzai** [comment]
@Yaelle01 I translated the title for both CAR and DRC so the HID should be pulling the english names now.

**Comment by javedyousafzai** [comment]
@Yaelle01 and @guillaumev can we close this case now?

**Comment by guillaumev** [comment]
@javedyousafzai Please keep it open for now, as I'd like to look into the Jordan issue a bit closer... I'll close it when I'm done. Thanks.

**Comment by javedyousafzai** [comment]
OK

**Comment by javedyousafzai** [comment]
@guillaumev , just spoke to @andrejverity . I have set 'Jordan' as country against the 'Jordan cross border'. will check with @Yaelle01 if this cause any issue in the HID Check-in countries.

**Comment by javedyousafzai** [comment]
@guillaumev can we close this case?
