### ISSUE TITLE
Regions as countries in HR.info

### ISSUE THREAD

**Issue by guillaumev** [humanitarianresponse/site#79]
There is a need for HID to show some of the HR.info regions as an option to checkin. Given that HID only pulls countries and not regions, in the past, as a quick fix, some regions were changed to countries in Humanitarianresponse, so that HID would pull them. This is not ideal however, as the information is displayed wrongly in the API, for example see:

https://www.humanitarianresponse.info/api/v1.0/operations/80

A better solution would be to add a checkbox showing whether an operation should appear in HID, and expose this checkbox in the API. HID would then pull all operations based on this checkbox.

**Comment by javedyousafzai** [comment]
in the API for the country it shows "type: "country", for the region, are you going to show type='region'?

**Comment by guillaumev** [comment]
it already shows type: region for the regions, see https://www.humanitarianresponse.info/api/v1.0/operations?filter[type]=region, it's just that some regions were changed to countries to make them show up in HID

**Comment by guillaumev** [comment]
The inactive option was added, I'm closing this.
