### ISSUE TITLE
Small issue in datasets migration

### ISSUE THREAD

**Issue by guillaumev** [humanitarianresponse/site#81]
Some datasets ended up with raw HTML after the migration to HDX (see below image)

![blob](https://cloud.githubusercontent.com/assets/90224/9684447/f98d811e-5317-11e5-845e-752b14a1a8f8.png)

**Comment by javedyousafzai** [comment]
@guillaumev shall I close this case?

**Comment by guillaumev** [comment]
@javedyousafzai Yes, I'm closing it.
