### ISSUE TITLE
Recover /operations/geojson page

### ISSUE THREAD

**Issue by pcambra** [humanitarianresponse/site#84]
Due to some changes in the views_geojson module, we're missing the Geojson display from the hr_operations view, see https://www.drupal.org/node/2531862

We need to drop the views_json display and review if any other views are using it and use the feed instead, check https://www.drupal.org/node/2528458 to see how this is done.

**Comment by javedyousafzai** [comment]
Martin, the UNICEF cluster map on http://nutritioncluster.net/work/countries/ is not loading data and they have not changed anything. Is it related to the this issue #84?

**Comment by MartinMaritim** [comment]
Let me have a look @javedyousafzai

**Comment by javedyousafzai** [comment]
@ramyzaki , can you check with your developer as well on the map issue in the Nutrition website http://nutritioncluster.net/work/countries/ 

The map cursor keeps running but it should atleast show the base layer.

**Comment by pcambra** [comment]
Closing this one, following up the nutrition map on #103
