### ISSUE TITLE
HR.info Dashboard for internal administration

### ISSUE THREAD

**Issue by javedyousafzai** [humanitarianresponse/site#89]
We need to develop a new feature as a Dashboard on the HR.info which should be accessible to Administrators or HR.info tech team to extract specific type of reports and analytics for advocacy, management and other reporting needs. See the full details in the Googledoc [HR.info Dashboard] (https://docs.google.com/document/d/1z34ptFpu2NzOC33kXXCLfz9xMmyZ1VcDUtdln3X2GIg/edit?usp=sharing)

**Comment by javedyousafzai** [comment]
@pcambra, I tried to assign this case to @MartinMaritim and @humphreymburu both but I am not sure if two people can assinged to one case at a time. 

this is not a high priority for now but we will need to work on it based on our prioritization.

**Comment by emmajane** [comment]
Closing this issue. Will be replaced by new tickets for Google Analytics integration.
