### ISSUE TITLE
Piwik: add widgets for popular content

### ISSUE THREAD

**Issue by javedyousafzai** [humanitarianresponse/site#93]
**2.Mostly viewed pages/content**. Don't know how hard this would be but this is one of the frequently asked stat type. We can limit this to 'top ten' mostly viewed/downloaded content within a given operation or cluster subspace. 

Outstanding Tasks:

- Create new tab for "Site content"
  - Add page widget -- see comments for URL format
- Create new tab for "Downloads"
  - Add download widget -- see comments for URL format
  - Move "Downloads" widget from the tab "Overview" to "Downloads"
- Ensure date range filter is available for the new tab "Site content"
- Rename tab "Settings" to "Browsers"

# Completed

Completed: ~~**1. Date Range:** We need to include the date range as some country offices wants to get their web analytic for very specific date.~~

# Previous notes

HI @pcambra, based on discussion this morning about the improvements for the stats, I just had a call with @MartinMaritim and we would like to include the following features to the work you are doing [stats issue#10 (https://github.com/humanitarianresponse/site/issues/10).

Download / page widget will provide browsable information, which is sufficient. ~~**3. Stats for specific content** - Get the stats for a given content (document, map, assessment) by specifying its URL. When a user wants to get the stats (views/downlaods, etc) for a specific content e.g. [WFP RAO Assessment_Bigu VDC_Dolakha] (https://www.humanitarianresponse.info/en/operations/nepal/assessment/150805wfp-rao-assessmentbigu-vdcdolakha), he/she should be able to get those figures by specifying the URL of that content.~~
Maybe we can separate this from the widgets you have already worked on and add a tab and call it 'Custom Analytics' and then they click on it, there will be an input field for the URL which they provide and then get the stats (viewed/downloaded).

The above three additions are the ones that everyone country offices is interested in and they ask for it, so If we are able to provide that, we will satisfy most of their needs and If they still request for very specific/custom analytics, we will continue doing it the same way as Martin has been doing it.

let me know If you want to talk further about it.

**Comment by javedyousafzai** [comment]
@pcambra I have checked with Andrej on the trello card for 'Analytics Improvements' (https://trello.com/c/LFH6Uwhk) and what I mentioned above were asked during the training so there wasn't anything new.

**Comment by pcambra** [comment]
I've split 1 into #95 because is a little different.

2 and 3 make sense to me, but we need to think were to put these (new tabs?) and if it makes sense to reorganise the tabs in the analytics screen somehow.

Maybe Overview should have just the graph stats and we should add "content" and a "downloads" tabs

**Comment by pcambra** [comment]
Download widget:

https://stats.humanitarianresponse.info/index.php?idSite=14&date=2015-11-30%2C2015-12-06&period=range&segment=customVariablePageName1%3D%3Dspaces%3BcustomVariablePageValue1%3D%4065&disableLink=1&module=Widgetize&action=iframe&widget=1&token_auth=e070af8189d85a2cdc91b12e8ce3d1e1&moduleToWidgetize=Actions&actionToWidgetize=menuGetDownloads&space_id=65&space_type


Page:

https://stats.humanitarianresponse.info/index.php?idSite=14&date=2015-11-30%2C2015-12-06&period=range&segment=customVariablePageName1%3D%3Dspaces%3BcustomVariablePageValue1%3D%4065&disableLink=1&module=Widgetize&action=iframe&widget=1&token_auth=e070af8189d85a2cdc91b12e8ce3d1e1&moduleToWidgetize=Actions&actionToWidgetize=menuGetPageUrls&space_id=65&space_type

**Comment by emmajane** [comment]
Date range is completed: ![2015-12-31 at 14 25](https://cloud.githubusercontent.com/assets/1299320/12065187/871e9220-afca-11e5-9287-5a4c5ca89d3d.png)

**Comment by emmajane** [comment]
Gorgeous! Checked in prod, and emailed already one IMO. Thanks, @pcambra ! This will make lots of people very, very happy! :)
