### ISSUE TITLE
Sort the search result - showing latest first 

### ISSUE THREAD

**Issue by javedyousafzai** [humanitarianresponse/site#94]
Hello Everyone, see the screenhot I took from [Afghanistan office website] (https://www.humanitarianresponse.info/operations/afghanistan/search?search=3w) when I was searching for the term '3W'. When they search for '3W' they expect the latest results to show first. When I tested, I see the results returned from 2014. 

I thought we dicussed it sometime ago in Atrium case, but tagging @guillaumev as he may want to add some comments to this one. 

Question: Can we change the search criteria and show the latest results and then the term relevance?

**Comment by guillaumev** [comment]
The initial request was to have search results sorted by publication date. However, not all content types have a publication date field. Therefore, the search results of the space or global search are sorted by relevancy, however the search results for documents & infographics are sorted by publication date.

**Comment by javedyousafzai** [comment]
OK thanks @guillaumev, that makes sense. As long as the documents/Maps are sorted by dates, its fine. I will explain to them how the sorting date works.
